name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r starter/requirements.txt

    - name: Run flake8
      run: |
        pip install flake8
        flake8 starter/starter --max-line-length=100 --extend-ignore=W291,W292,W391,E302,E305,F401
    - name: Run pytest
      run: |
        pytest starter/starter/test_model.py starter/starter/test_api.py -v